# Earnings Manipulation Case
Predicting Earnings Manipulation by Indian Firms using Machine Learning Algorithms

This is a python notebook constructed by Angel Oganesian, Charlotte Vercammen, Lennert Van der Schraelen, and Prof. Dr. Kristof Stouthuysen. All authors are members of the **[Centre for Financial Leaderschip and Digital Transformation](https://www.vlerick.com/en/for-companies/research-for-your-company/centre-for-financial-leadership-and-digital-transformation/)** at **Vlerick Business School**.

## 1. Case Introduction

### Context

- A private bank is concerned that their customers may be involved in **Earnings Manipulations** to increase their chances of securing a loan.
- **Definition**:  
    *When a management takes deliberate steps to bring reported earnings to a desired level, it is called earnings manipulations.*
    
<center><img src="https://cdn-icons-png.flaticon.com/512/5223/5223830.png" width="25%" style="float:right"></center>

## 2. Exam Instructions

Please read the exam instructions (see zip-file on Canvas) thoroughly and ensure you understand the difference between the two datasets provided:

1. **`training_data.csv`**: This dataset includes known labels and is to be used for training and validating your model.

2. **`testing_data.csv`**: This dataset does not include true labels. It will be used to grade your model's performance.

Both datasets are already loaded in this notebook! See below.

In [ ]:
import pandas as pd

In [ ]:
# Loading training data

%%capture

# download data from google drive to colab
!wget https://drive.google.com/uc?id=1bKxPj-rgCbX1CdCaI7h2ltWGuU76HnPG -O training_data.csv

df_train = pd.read_csv("training_data.csv", index_col=0)

In [ ]:
df_train.head()   # We take a look at the first 5 observations in the dataset

,DSRI,GMI,AQI,SGI,DEPI,SGAI,TATA,LEVI,Manipulate
0,1.035281,1.304182,1.475950,1.203238,1.025079,1.078618,-0.109538,0.831817,0
1,0.945277,0.063649,-4.187126,1.204269,1.318483,1.225752,0.024110,1.107922,0
2,1.046727,0.999956,1.159317,1.045805,1.034746,1.138764,-0.057101,1.015526,0
3,1.046441,1.019219,2.581805,1.062977,1.013479,0.826245,0.089859,2.385649,0
4,0.522516,0.939116,0.746989,1.289868,0.818491,1.083156,0.137976,1.128543,0

In [ ]:
# Loading testing data

%%capture

# download data from google drive to colab
!wget https://drive.google.com/uc?id=1tdeqQGmhVQhd2AzbALlUmTiJSxA2cAUA -O testing_data.csv

df_testing = pd.read_csv("testing_data.csv", index_col=0)

In [ ]:
df_testing.head()   # We take a look at the first 5 observations in the dataset

,DSRI,GMI,AQI,SGI,DEPI,SGAI,TATA,LEVI
0,1.275311,0.254632,2.112682,0.670018,1.074884,1.545288,-0.062813,1.005203
1,0.793550,1.021763,1.024078,1.169028,0.493253,0.952784,-0.084953,0.977136
2,2.724623,1.849300,0.653566,0.354558,1.107652,1.286774,-0.126043,2.085140
3,1.506583,1.074532,1.296223,1.106679,1.049747,0.920142,-0.187968,1.339111
4,0.842003,0.777791,4.094086,1.082125,0.264310,0.853473,-0.075476,1.063462